version: '2'
services:
  nginx:
    image: amsdard.io/{name}/nginx:1.0
    stdin_open: true
    tty: true
    links:
    - php:php
    - redis:redis
    labels:
      traefik.enable: 'true'
      traefik.domain: app.amsdard.io
      io.rancher.container.pull_image: always
      traefik.alias: {name}
  php:
    image: amsdard.io/{name}/php:1.0
    environment:
    stdin_open: true
    tty: true
    links:
    - mysql:mysql
    labels:
      io.rancher.container.pull_image: always
  mysql:
    image: mariadb
    environment:
    stdin_open: true
    volumes:
    - {name}-mysql-var-lib-mysql:/var/lib/mysql
    tty: true
  redis:
    image: redis:alpine
    stdin_open: true
    tty: true